### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by EdgarMontelo** [functionreturnfunction/G27_Pedals_and_Shifter#16]
I dont know whats to do

Arduino: 1.8.5 (Windows 7), Placa:"Arduino/Genuino Micro"

Opções de compilação alteradas, recompilando tudo
D:\USER\Downloads\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter.ino:8:36: fatal error: ./lib/G27PedalsShifter.h: No such file or directory

 #include "./lib/G27PedalsShifter.h"

                                    ^

compilation terminated.

**Comment by per1234** [comment]
I have submitted a pull request to fix this problem: https://github.com/functionreturnfunction/G27_Pedals_and_Shifter/pull/17
