### ISSUE TITLE
Very new to this

### ISSUE THREAD

**Issue by The-Bandit** [functionreturnfunction/G27_Pedals_and_Shifter#19]
this is what im getting as far as an error message. I'm not sure where to go from here as I'm very new to this.
Arduino: 1.8.7 (Windows Store 1.8.15.0) (Windows 10), Board: "Arduino Pro or Pro Mini, ATmega328P (5V, 16 MHz)"

In file included from D:\TheBandits\Documents\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter.ino:8:0:

c:\users\theban~1\appdata\local\temp\arduino_build_954244\sketch\lib\g27pedalsshifter.h:30:2: warning: #warning "Using legacy HID core (non pluggable)" [-Wcpp]

 #warning "Using legacy HID core (non pluggable)"

  ^

D:\TheBandits\Documents\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter.ino:122:1: warning: 'typedef' was ignored in this declaration

 };

 ^

D:\TheBandits\Documents\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter.ino: In function 'void setXAxis(void*)':

G27_Pedals_and_Shifter:184:3: error: 'G27' was not declared in this scope

   G27.setXAxis(input->axis);

   ^

D:\TheBandits\Documents\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter.ino: In function 'void setYAxis(void*)':

G27_Pedals_and_Shifter:189:3: error: 'G27' was not declared in this scope

   G27.setYAxis(input->axis);

   ^

D:\TheBandits\Documents\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter.ino: In function 'void setZAxis(void*)':

G27_Pedals_and_Shifter:194:3: error: 'G27' was not declared in this scope

   G27.setZAxis(input->axis);

   ^

D:\TheBandits\Documents\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter.ino: In function 'void setButtonStates(int*, int)':

G27_Pedals_and_Shifter:290:5: error: 'G27' was not declared in this scope

     G27.setButton(i, LOW);

     ^

G27_Pedals_and_Shifter:294:5: error: 'G27' was not declared in this scope

     G27.setButton(gear - 1, HIGH);

     ^

G27_Pedals_and_Shifter:298:5: error: 'G27' was not declared in this scope

     G27.setButton(buttonTable[i], buttons[i]);

     ^

D:\TheBandits\Documents\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter.ino: In function 'void setup()':

G27_Pedals_and_Shifter:359:3: error: 'G27' was not declared in this scope

   G27.begin(false);

   ^

D:\TheBandits\Documents\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter.ino: In function 'void loop()':

G27_Pedals_and_Shifter:438:3: error: 'G27' was not declared in this scope

   G27.sendState();

   ^

exit status 1
'G27' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by hgreen1** [comment]
Hey Bandit.

Make sure you've selected the correct board in the arduino software. in the menubar, in the menu bar you need to click Tools -> Boards -> Sparkfun Pro Micro. Also, make sure you pick the correct frequency and communication port.
