### ISSUE TITLE
Schematic for soldering

### ISSUE THREAD

**Issue by MathijsG** [functionreturnfunction/G27_Pedals_and_Shifter#2]
Hi,

Where can I find a graphical schematic for soldering this? I really like this project. I have a G27 wheel set without the wheel, and I don't think I will get the wheel easily so I want to use this project to hook the shifter and pedals to my pc, while using my old MOMO wheel.

Does the clutch also still function like it does with the G27? For shifting?

**Comment by deiteris** [comment]
You don't need scheme to do it. Just buy any ATMega32u4 with Arduino Leonardo bootloader, get few wires, place and solder them according to pinout table provided in sketch, connect to ports (or you can cut connectors and solder them directly to board, if you don't have any warranty and don't afraid to solder them back), adjust some values if you need, compile and upload sketch. And congrats, you got shifter and pedals working without base.
That's how it works for me. Additional ground was soldered for testing purposes. Figured out that I may attach only one to 6 or 9 pin and it will work fine.
![img_20160825_162847](https://cloud.githubusercontent.com/assets/6103913/17979940/b0f90d4a-6b05-11e6-89f5-bb82fb986369.jpg)

**Comment by MathijsG** [comment]
Nice. I saw a shitload of resistors on the main page. That's why :-). I will try the schematic once I have the connector.

**Comment by erkan377** [comment]
![unknown](https://user-images.githubusercontent.com/85454251/153015526-0e8b334c-b3ed-423d-beab-8f52f39db375.png)
![unknown](https://user-images.githubusercontent.com/85454251/153015529-4a9eb1c2-bb86-4ea1-9dbb-db097fcc874a.png)
