### ISSUE TITLE
G27 Shifter work but

### ISSUE THREAD

**Issue by XTream87** [functionreturnfunction/G27_Pedals_and_Shifter#22]
Hello, I have one issue. In driver check when I switch to 1,3,5 gear it works like Z axis and it moves direction axis. How can I modified it to non-axis mode only buttons?

**Comment by XTream87** [comment]
This makes some trouble in games.

**Comment by functionreturnfunction** [comment]
I'm not sure I understand what you're asking? The device converts the shifter axes into button presses which the game sees.

**Comment by XTream87** [comment]
Yes, but else it have Z axis in driver, which also moves with 1st, 3rd and 5th gear. And some games interpret it like I move some axis.

**Comment by functionreturnfunction** [comment]
The only axes sent to the PC are controlled by the pedals, it sounds to me like you may have a bad or crossed connection somewhere.

**Comment by XTream87** [comment]
Sorry, my bad! I forgot to comment pedals definition!
