### ISSUE TITLE
Shifter button problems

### ISSUE THREAD

**Issue by pedromelim** [functionreturnfunction/G27_Pedals_and_Shifter#8]
Shifter buttons from 8 to 19 are always pressed and i cant find where the issue is, also when using 6th and 7th gear, it will always do 7th gear. All conections are done but somehow thsi doesnt worked. I tried looking at the code for several hours but nothing found, could you help me out?
![shifter problem](https://cloud.githubusercontent.com/assets/11959992/19890965/b0d188d2-a035-11e6-87a3-a52f0a571bc2.jpg)

**Comment by pedromelim** [comment]
After alot of time lost, just realized that the pins 0 and 1 on the arduino are switched, tought it start 0, 1, 2 etc, but its 1, 0, 2 etc...im not at home but im sure thats the problem. feel such a noob ;)

**Comment by functionreturnfunction** [comment]
Sorry I didn't get back sooner, but yeah, those buttons are wired on a matrix so the fact that you see any of them triggering at all makes me think you must have a pin switched or a short somewhere.  Good luck!
